# fly.toml app configuration file generated for artbot on 2025-11-26T06:46:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'artbot'


[build]
  builder = "heroku/builder:22"

[deploy]
  strategy = "immediate"


[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

